name: Build Windows EXE

on: [push]

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
    - name: Kód letöltése
      uses: actions/checkout@v4

    - name: Python beállítása
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'
        architecture: 'x64'

    - name: Függőségek telepítése (PyInstaller és requirements)
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: test-placcon-display.exe buildelése (test.core.placcon.com)
      run: |
        pyinstaller --onefile --windowed --icon="placcon.ico" --name "test-placcon-display" launch_placcon.py -- "test.core.placcon.com"

    - name: placcon-display.exe buildelése (core.placcon.com)
      run: |
        pyinstaller --onefile --windowed --icon="placcon.ico" --name "placcon-display" launch_placcon.py -- "core.placcon.com"

    - name: Buildelt Exék feltöltése artifactként
      uses: actions/upload-artifact@v4
      with:
        name: Windows-Placcon-Executables
        path: |
          dist/test-placcon-display.exe
          dist/placcon-display.exe 